### ISSUE TITLE
PublisServiceTest fails on OSX due to newline characters

### ISSUE THREAD

**Issue by bestalign** [getscissorhands/Scissorhands.NET#66]
https://github.com/getscissorhands/Scissorhands.NET/blob/dev/test/Scissorhands.Services.Tests/PublishServiceTest.cs#L131

The line above failed because of `\r\n` on OSX. I've updated it to `\n` and the test succeeded. Here is the error logs:
```
xUnit.net DNX Runner (64-bit DNXCore 5.0)
  Discovering: Scissorhands.Services.Tests
  Discovered:  Scissorhands.Services.Tests
  Starting:    Scissorhands.Services.Tests
    Scissorhands.Services.Tests.PublishServiceTest.Given_Model_ApplyMetadata_ShouldReturn_Result(title: "Hello World", slug: "hello-world", author: "Joe Bloggs", tags: "hello,world", body: "**Hello World**") [FAIL]
      Expected string that ends with equivalent of "**Hello World**\r\n", but found "---\n* Title: Hello World\n* Slug: hello-world\n* Author: Joe Bloggs\n* Date Published: 2/29/2016 1:45:39 AM\n* Tags: hello, world\n---\n\n**Hello World**\n".
      Stack Trace:
           at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message)
           at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
           at FluentAssertions.Primitives.StringAssertions.EndWithEquivalent(String expected, String because, Object[] reasonArgs)
           at Scissorhands.Services.Tests.PublishServiceTest.Given_Model_ApplyMetadata_ShouldReturn_Result(String title, String slug, String author, String tags, String body)
  Finished:    Scissorhands.Services.Tests
=== TEST EXECUTION SUMMARY ===
   Scissorhands.Services.Tests  Total: 32, Errors: 0, Failed: 1, Skipped: 0, Time: 1.548s
```

**Comment by justinyoo** [comment]
Merged. :+1:
